### ISSUE TITLE
API seems incomplete

### ISSUE THREAD

**Issue by eike-welk** [anentropic/ebaysuds#2]
I'm trying to use a call from the Finding API: findItemsByKeywords [1], however it seem not to be implemented in Ebaysuds.

[1] http://developer.ebay.com/DevZone/finding/CallRef/findItemsByKeywords.html

This little snippet does not work:

``` python
from ebaysuds import EbaySuds
client = EbaySuds()
response = client.findItemsByKeywords(keywords="Superman")
```

It raises the exception:

```
suds.MethodNotFound: Method not found: 'eBayAPIInterfaceService.eBayAPI.findItemsByKeywords'
```

The basic idea of this library is great: The work to maintain the API library is now done by Ebay. But they are maybe sloppy or slow to update their machine readable documentation.

**Comment by anentropic** [comment]
Seems like the Finding API is a separate web service, it has its own WSDL (http://developer.ebay.com/devzone/finding/Concepts/MakingACall.html#SchemaLocation) and possibly a different call structure so may need its own client.

**Comment by eike-welk** [comment]
Ah, OK so there is room to grow for Ebaysuds. I'll post a whishlist that you cover all APIs, so that we can do in the future:

``` python
from ebaysuds import  TradingAPI,  FindingAPI
```
