### ISSUE TITLE
Implement more APIs

### ISSUE THREAD

**Issue by eike-welk** [anentropic/ebaysuds#3]
Ebaysuds seems currently only to implement the trading API. Please implement more of the Ebay APIs. Especially implement the finding API, because finding functionality does not exist in the trading API, or is deprecated.

I also would like a small change in your API so that in the future we could issue:

``` python
from ebaysuds import  TradingAPI,  FindingAPI
```

**Comment by anentropic** [comment]
true, looks like we also need `ShoppingAPI`

**Comment by anentropic** [comment]
@eike-welk ...there is now experimental support for the Finding API and the Shopping API in the `multi-apis` branch. I have refactored it exactly how we proposed above, i.e.

`from ebaysuds import TradingAPI, FindingAPI, ShoppingAPI`

I have tried a few simple calls against each API and they seem to be basically working. I expect there may be some things I've missed.

If you have time to try out the other API that you needed and send any feedback or bugs found that's much appreciated.

**Comment by eike-welk** [comment]
That's really great!

However I have now settled to use Python-Ebay. I won't switch over to Ebaysuds anytime soon, even though I think it is technically superior. 

I'll see that I port the tests for the finding API, that I wrote for Python-Ebay, to Ebaysuds sometime.

**Comment by anentropic** [comment]
have released v0.4.1 to pypi, adding support for these three APIs
