### ISSUE TITLE
Support different API Versions

### ISSUE THREAD

**Issue by eike-welk** [anentropic/ebaysuds#4]
The Ebay API constantly changes, but Ebay supports old versions of the API for 18 months. If Ebaysuds always downloads the latest version of the API description, the generated API changes over time. This can lead to mysterious bugs in client software.

Therefore Ebaysuds should have a way to support old versions of the API.

This may be done by requesting old versions of the API description (I have no knowledge of SOAP), or by storing a specific API description on disk.

**Comment by anentropic** [comment]
You can supply your own version of the WSDL:
https://github.com/anentropic/ebaysuds/blob/master/ebaysuds.conf-example

**Comment by eike-welk** [comment]
Some documentation how one can download the WSDL file would be quite helpful.
