### ISSUE TITLE
Setting configuration options dynamically

### ISSUE THREAD

**Issue by petra-design** [anentropic/ebaysuds#6]
How can I set the auth token dynamically, for a request, if I have several of them?

should it be something like
from ebaysuds import config

config.production_config.items(something) ... ?

Or in an other way?

Thanks a lot!

**Comment by anentropic** [comment]
You can pass the credentials in when instantiating the api client, which will override values from the config file

eg

```
from ebaysuds import TradingAPI

client1 = TradingAPI(token="MM69874N98787$1299ICB")
client2 = TradingAPI(token="BV3686GHFS568TD69HX9$")

client1.GetItem(ItemID="321021906488")
client2.GetItem(ItemID="321021906489")
```

**Comment by petra-design** [comment]
Exactly what I needed. Thanks a lot!
